version: '3.8'

services:
  app:
    build: .
    container_name: express-app
    ports:
      - 3000:3000
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/employees
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.6
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db